@startuml ClassDiagram

class Person

class Account
class Customer
class SystemAdmin
class Shipper
class ShopOwner

Person  <|--  Customer
Person  <|--  SystemAdmin
Person  <|--  Shipper
Person  <|--  ShopOwner


Account "1" -- "1" Customer
Account "1" -- "1" SystemAdmin
Account "1" -- "1" Shipper
Account "1" -- "1" ShopOwner


class Order
class OrderDetail
class OrderItem
class Payment
class Cash

Payment <|-- Cash

Order "1" *-- "1" OrderDetail
Order "1...*" -- "1" Customer : "create"
Order "1...*" -- "1" Shipper : "deliver"
Order "1...*" -- "1" Store : "prepare"

OrderDetail "1" *-- "1...*" OrderItem : contains
OrderDetail "1" *-- "1" Payment

class Store
class StoreChain
class Menu

Store "1...*" --* "1" StoreChain
Store "1" *-- "1" Menu
Menu "1" *-- "1...*" OrderItem : "contains"

class Discount
class DiscountDetail

OrderDetail "1" *-- "1...*" Discount
Discount "1" *-- "1" DiscountDetail

@enduml
