@startuml Review Class Diagram

class Account
class Order

class Review

class Store
class StoreChain
Store "1...*" --* "1" StoreChain

Order "1" o-- "1" Review
Account "1" o-- "1" Review
Store "1" o-- "1" Review

@enduml
